### ISSUE TITLE
Button how showing in version 1.5.0 of Flarum

### ISSUE THREAD

**Issue by Benoit1980** [FriendsOfFlarum/share-social#31]
Hello,

I would like to report a bug.

\Flarum
1.5.0PHP
8.1.7MySQL
10.5.16-MariaDB
Share of Social version: 1.1.0

The share button is not showing anywhere.
I cleared the cache but nothing at all.

Also your image example on this page are not available anymore(under "screenshots"):
https://extiverse.com/extension/fof/share-social

Thank you!

**Comment by datitisev** [comment]
Have you enabled any of the sharing services? The button won't appear if you don't have any enabled.
